### ISSUE TITLE
编译失败，能否将编译后的版本提供下呢

### ISSUE THREAD

**Issue by hadi33** [totoro52/rbnb-gpu-miner#1]
D:\Program Files\CUDA\bin/../include\cuda.h(21758): warning C4819: 该文件包含不能在当前代码页(936)中表示的字符。请将该文件保存为 Unicode 格式以防止数据丢失
main.cu(53): error: expected a declaration
  {
  ^

main.cu(117): error: identifier "hex_string_to_char_array" is undefined
          hex_string_to_char_array(res, data);
          ^

2 errors detected in the compilation of "main.cu".

**Comment by totoro52** [comment]
请使用最新的cuda版本重新编译一下看看，代码是测试通过才上传的
