### ISSUE TITLE
你好，请问这个挖矿是https://bnb.reth.cc/平台的挖矿吗

### ISSUE THREAD

**Issue by yeshili** [totoro52/rbnb-gpu-miner#2]
你好，请问这个挖矿是https://bnb.reth.cc/平台的挖矿吗，看main里面又有这个请求相关地址配置的

**Comment by totoro52** [comment]
是的， 该程序只负责碰撞出对应的hash值，还需要自行上传给平台，GPU计算不涉及网络

**Comment by yeshili** [comment]
你的意思，不会自动打到address钱包吗

**Comment by totoro52** [comment]
是的，RBNB和其他铭文不同，你必须和他的后端交互，而不是直接和链交互

**Comment by yeshili** [comment]
这样子搞出来，对于不懂这个语言得代码，都没法用。弄出hash也没用呀

**Comment by totoro52** [comment]
抱歉，这是我一个实验性的脚本，需要搭配其他脚本一起使用，你可以根据输出的result文件自行编写脚本处理即可。

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/cc0800f2-b791-467c-9cb9-05f7c2f82092)
这里填写地址，还以为可以直接跑起来，会把打到得，直接回处理到该账户

**Comment by yeshili** [comment]
那你应该把文档说明清楚点5555
