### ISSUE TITLE
你好，怎么执行出现这个错误呢

### ISSUE THREAD

**Issue by yeshili** [totoro52/rbnb-gpu-miner#3]
c++和CUDA Toolkit也安装了
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/dca9a395-1787-4c68-94ee-c15391e85f44)

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/59d140d3-8864-4f2b-8a16-296fbaae5992)

**Comment by totoro52** [comment]
nvcc指令没找到，可能你的cuda并没有配置到path

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/2eb66c3d-b5a8-44fd-a085-afb84514

配置了，但是都是执行错误，心碎！

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/acb139c1-cc12-4dba-83aa-84a52d0539c9)

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/654d8797-06b4-4291-9c9a-917fa247310c)

**Comment by totoro52** [comment]
这些只是警告

**Comment by yeshili** [comment]
![image](https://github.com/totoro52/rbnb-gpu-miner/assets/24773628/887a2c25-f5db-40d8-886c-37e6fa68b4d3)

**Comment by totoro52** [comment]
nvcc *.obj -o main.exe
如果执行不行，就把*换成每一个obj

**Comment by yeshili** [comment]
直接把.cu后缀改成obj吗
